### PR TITLE
Replaced outdated page with link to my website

### PR DESCRIPTION
**Pull request by JackLaSota**
I don't want to have to keep my page here up-to-date. My website is better. Need someone to review my changes to the page with the list of thumbnails, and make sure they didn't break things when I took my game out of the automatically-generated ordered list. If I did this correctly, the image which used to link to the page on my game will now go directly to http://dystheism.net/.

### CODE REVIEW

**Comment by LUKK3** [comment]
Whoops I guess I should have been checking this repo over the summer.
It doesn't look like you've changed any files other than removing an image, but I did a separate commit so that it now links to your site.

**Comment by JackLaSota** [comment]
Thanks Luke, can you also take down the outdated page itself so it doesn't
show up in google results for "Dystheism Game", or advise me on how to do
it?
(It looks like the link and thumbnail is generated by the same file that
generates the page, so maybe slightly tricky?)
https://www-s.acm.illinois.edu/gamebuilders/games/2013/11/20/dystheism.html

**Comment by LUKK3** [comment]
Okay, I removed it manually, though it still shows up on google leading to a 404.

**Comment by JackLaSota** [comment]
Alright, hopefully google will update eventually.
Thanks again.

**Pull request closed without merging**
